# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title: The Lesser Key of St. Byleth
tagline: A lovely site.
description: >- # this means to ignore newlines until "baseurl:"
  A dusty tome, speaking in tongues.
domain: saintbyleth.github.io
baseurl: "" # the subpath of your site, e.g. /blog
url: https://saintbyleth.github.io # the base hostname & protocol for your site, e.g. http://example.com

paginate: 5
permalink: /:year/:month/:day/:title:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

sidebar_home_link:  true
disqus.shortname: saintbyleth

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
